### ISSUE TITLE
Get the same error when trying to search unicode

### ISSUE THREAD

**Issue by yam-liu** [aswild/the_silver_searcher#1]
ERR: Bad regex! pcre_compile() failed at position 10: PCRE2 does not support \F, \L, \l, \N{name}, \U, or \u

Does pcre2 support unicode with \uxxx ? Thanks.

**Comment by aswild** [comment]
Have you checked the PCRE2 documentation?

**Comment by yam-liu** [comment]
Yes, it is said supported. Maybe I use it in a wrong way? I will attach the command tomorrow.

**Comment by aswild** [comment]
See https://www.pcre.org/current/doc/html/pcre2unicode.html

> To process a pattern as a UTF string, where a character may require more than one code unit, you must call pcre2_compile() with the PCRE2_UTF option flag, or the pattern must start with the sequence (*UTF).


> The escape sequence \N{U+<hex digits>} is recognized as another way of specifying a Unicode character by code point in a UTF mode. It is not allowed in non-UTF modes.

In other words, to match multi-byte unicode characters, you must start your pattern with `(*UTF)` and use `\N{U+xxxx}` instead of `\uxxxx`.

I did a quick benchmark and for me UTF matching was ~34% slower than non-UTF matching (for an ASCII-only pattern), so I will not be enabling it by default.

**Comment by yam-liu** [comment]
Thanks. I have already used rg to finish my work. I will try it like you
said.
Allen Wild <notifications@github.com>于2018年11月13日 周二00:37写道：
